import torch
import pandas as pd


#A list of all teams
all_team_names = [
    "Ajaccio",
    "Alaves",
    "Almeria",
    "Amiens",
    "Angers",
    "Arsenal",
    "Aston Villa",
    "Atalanta",
    "Ath Bilbao",
    "Ath Madrid",
    "Augsburg",
    "Auxerre",
    "Barcelona",
    "Bayern Munich",
    "Benevento",
    "Betis",
    "Bielefeld",
    "Bochum",
    "Bologna",
    "Bordeaux",
    "Bournemouth",
    "Brentford",
    "Brescia",
    "Brest",
    "Brighton",
    "Burnley",
    "Cadiz",
    "Cagliari",
    "Celta",
    "Chelsea",
    "Clermont",
    "Como",
    "Cremonese",
    "Crotone",
    "Crystal Palace",
    "Darmstadt",
    "Dijon",
    "Dortmund",
    "Eibar",
    "Ein Frankfurt",
    "Elche",
    "Empoli",
    "Espanol",
    "Everton",
    "FC Koln",
    "Fiorentina",
    "Fortuna Dusseldorf",
    "Freiburg",
    "Frosinone",
    "Fulham",
    "Genoa",
    "Getafe",
    "Girona",
    "Granada",
    "Greuther Furth",
    "Hamburg",
    "Heidenheim",
    "Hertha",
    "Hoffenheim",
    "Holstein Kiel",
    "Huesca",
    "Inter",
    "Ipswich",
    "Juventus",
    "Las Palmas",
    "Lazio",
    "Le Havre",
    "Lecce",
    "Leeds",
    "Leganes",
    "Leicester",
    "Lens",
    "Levante",
    "Leverkusen",
    "Lille",
    "Liverpool",
    "Lorient",
    "Luton",
    "Lyon",
    "M'gladbach",
    "Mainz",
    "Mallorca",
    "Man City",
    "Man United",
    "Marseille",
    "Metz",
    "Milan",
    "Monaco",
    "Montpellier",
    "Monza",
    "Nantes",
    "Napoli",
    "Newcastle",
    "Nice",
    "Nimes",
    "Norwich",
    "Nott'm Forest",
    "Osasuna",
    "Oviedo",
    "Paderborn",
    "Paris FC",
    "Paris SG",
    "Parma",
    "Pisa",
    "RB Leipzig",
    "Real Madrid",
    "Reims",
    "Rennes",
    "Roma",
    "Salernitana",
    "Sampdoria",
    "Sassuolo",
    "Schalke 04",
    "Sevilla",
    "Sheffield United",
    "Sociedad",
    "Southampton",
    "Spal",
    "Spezia",
    "St Etienne",
    "St Pauli",
    "Strasbourg",
    "Stuttgart",
    "Sunderland",
    "Torino",
    "Tottenham",
    "Toulouse",
    "Troyes",
    "Udinese",
    "Union Berlin",
    "Valencia",
    "Valladolid",
    "Vallecano",
    "Venezia",
    "Verona",
    "Villarreal",
    "Watford",
    "Werder Bremen",
    "West Brom",
    "West Ham",
    "Wolfsburg",
    "Wolves"
]

# Converts a football match sequence DataFrame into a PyTorch tensor suitable for ML models:
#   -Drops the 'Date' and 'Referee" column as they are not used in modeling.
#   -Encodes categorical outcome columns ('FTR' and 'HTR') into numeric codes.
#   -Encodes team names ('HomeTeam' and 'AwayTeam') into numeric codes based on all_team_names.
#   -Converts the entire DataFrame into a PyTorch tensor of type float
def sequence_to_tensor(sequence: pd.DataFrame):
    sequence = sequence.drop(columns=["Date","Referee"])
    sequence["FTR"] = pd.Categorical(sequence["FTR"], categories=["H","D","A"]).codes
    sequence["HTR"] = pd.Categorical(sequence["HTR"], categories=["H","D","A"]).codes
    sequence["HomeTeam"] = pd.Categorical(sequence["HomeTeam"], categories=all_team_names).codes
    sequence["AwayTeam"] = pd.Categorical(sequence["AwayTeam"], categories=all_team_names).codes
    return torch.tensor(sequence.values,dtype=torch.float)

